name: C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up environment
      run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          # Replace the missing PPA with official Qt installation
          sudo apt-get install -y qtbase5-dev qt5-default qttools5-dev-tools
        
    - name: Build project
      run: |
        mkdir build
        cd build
        cmake ..
        make
        
    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure

