name: C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Install Qt6 and dependencies from Ubuntu repositories
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          qt6-base-dev \
          qt6-base-dev-tools \
          qt6-multimedia-dev \
          libqt6multimedia6 \
          libqt6multimediawidgets6 \
          cmake \
          build-essential \
          libgl1-mesa-dev \
          libglu1-mesa-dev \
          pkg-config
        
    - name: Set Qt6 environment variables
      run: |
        echo "CMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu/cmake/Qt6:/usr/lib/x86_64-linux-gnu/cmake/Qt6Multimedia" >> $GITHUB_ENV
        echo "Qt6_DIR=/usr/lib/x86_64-linux-gnu/cmake/Qt6" >> $GITHUB_ENV
        echo "Qt6Multimedia_DIR=/usr/lib/x86_64-linux-gnu/cmake/Qt6Multimedia" >> $GITHUB_ENV
        
    - name: Debug Qt6 installation
      run: |
        echo "Qt6 installation check:"
        find /usr -name "Qt6*Config.cmake" 2>/dev/null || true
        find /usr -name "*Qt6Multimedia*" 2>/dev/null || true
        pkg-config --list-all | grep -i qt6 || true
        
    - name: Fix case sensitivity issues
      run: |
        # Fix include statements case sensitivity
        find . -name "*.cpp" -o -name "*.h" | xargs sed -i 's/#include "passwordTextEdit\.h"/#include "passwordtextedit.h"/g'
        
    - name: Build project
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=ON
        make -j$(nproc)
        
    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure
